# builds:
# - binary: synology-csi-driver
#   env:
#   - CGO_ENABLED=0
#   goos:
#   - linux
#   goarch:
#   - amd64
#   - arm
#   - arm64
#   goarm:
#   - 7

builds: []

env_files:
  github_token: .github.token.env

# signs:
#   - artifacts: checksum
#     args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

dockers:
- image_templates:
  - ghcr.io/${{ github.repository_owner }}/{{ .ProjectName }}:{{ .Tag }}-amd64
  dockerfile: Dockerfile
  goos: linux
  goarch: amd64
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .Tag }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
  extra_files:
  - Makefile
  - pkg
  - synocli
  - chroot
  - main.go
  - go.sum
  - go.mod

- image_templates:
  - ghcr.io/${{ github.repository_owner }}/{{ .ProjectName }}:{{ .Tag }}-arm
  goos: linux
  goarch: arm
  goarm: 7
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
  extra_files:
  - Makefile
  - pkg
  - synocli
  - chroot
  - main.go
  - go.sum
  - go.mod

- image_templates:
  - ghcr.io/${{ github.repository_owner }}/{{ .ProjectName }}:{{ .Tag }}-arm64
  goos: linux
  goarch: arm64
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
  extra_files:
  - Makefile
  - pkg
  - synocli
  - chroot
  - main.go
  - go.sum
  - go.mod

docker_manifests:
- name_template: ghcr.io/${{ github.repository_owner }}/{{ .ProjectName }}:{{ .Tag }}
  image_templates:
  - ghcr.io/${{ github.repository_owner }}/{{ .ProjectName }}:{{ .Tag }}-amd64
  - ghcr.io/${{ github.repository_owner }}/{{ .ProjectName }}:{{ .Tag }}-arm64v8
  - ghcr.io/${{ github.repository_owner }}/{{ .ProjectName }}:{{ .Tag }}-arm

- name_template: ghcr.io/${{ github.repository_owner }}/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/${{ github.repository_owner }}/{{ .ProjectName }}:{{ .Tag }}-amd64
  - ghcr.io/${{ github.repository_owner }}/{{ .ProjectName }}:{{ .Tag }}-arm64v8
  - ghcr.io/${{ github.repository_owner }}/{{ .ProjectName }}:{{ .Tag }}-arm

